// This file is autogenerated. Changes will be overwritten.
#include <DW4F2VDUYN/moc_DisplayWidget.cpp>
#include <DW4F2VDUYN/moc_FilterWidget.cpp>
#include <DW4F2VDUYN/moc_MainWindow.cpp>
#include <DW4F2VDUYN/moc_SourceWidget.cpp>
