// This file is autogenerated. Changes will be overwritten.
#include <V7OEQZMVFY/moc_Brain.cpp>
#include <V7OEQZMVFY/moc_LoadDataWidget.cpp>
#include <V7OEQZMVFY/moc_MainWindow.cpp>
#include <V7OEQZMVFY/moc_TrainWidget.cpp>
